### ISSUE TITLE
Table and Text layout 

### ISSUE THREAD

**Issue by Avichal-Malhotra** [ibpsa/project1-wp-2-1-cim-gis#15]
I think the we should have to be centered. In my opinion, it looks a bit strange right now. @julianbischof @GersHub

**Comment by julianbischof** [comment]
I am not sure, centred is the best option. What about aligned at the left cell border?

**Comment by Avichal-Malhotra** [comment]
I guess we need to try and see if this works. I am not sure either.

**Comment by Avichal-Malhotra** [comment]
I will close this for now.
