### ISSUE TITLE
PHP inplace of HTML

### ISSUE THREAD

**Issue by Avichal-Malhotra** [ibpsa/project1-wp-2-1-cim-gis#6]
Since in the python scripts we do convert the markdown files into HTML, my suggestion would be to transform them into PHP file and hence it will be more dynamic. 
As an example: In place of Contribute.html --> Contribute.php would be more dynamic in nature.

**Comment by GersHub** [comment]
Sounds good to me.... but: I have no clue about php :)

**Comment by Avichal-Malhotra** [comment]
The layout is almost the same, but  PHP helps in connecting to the server side. I will make the first draft for the Contribute page.

**Comment by Avichal-Malhotra** [comment]
I tried working around the html version of the contribute, however, there was again the issue of the php with Github. Could you try to deploy it and  see if it works? @GersHub.

The page to the links is also updated.

**Comment by julianbischof** [comment]
Do I remember correctly, that there might be an option of running php on an other GIT repository? @GersHub @Avichal-Malhotra

**Comment by julianbischof** [comment]
Alternatively we can allow that people contribute via updateing the template or the national data csv files? @GersHub @Avichal-Malhotra

**Comment by Avichal-Malhotra** [comment]
@julianbischof Yes there is atleast on Github. Moreover, the whole web structure is based on a python script so I am not quite sure if this is gonna work with PHP.

**Comment by Avichal-Malhotra** [comment]
> Alternatively we can allow that people contribute via updateing the template or the national data csv files? @GersHub @Avichal-Malhotra

Do you mean just updating the data? So here again, either we need to have a User management system, which in my opinion, will make more work for everyone. On the otherside, we can provide some email ids to send the data to. But again some people need to be responsible for this.

**Comment by Avichal-Malhotra** [comment]
We continue developing in the same way as earlier..
